<a href="https://colab.research.google.com/github/amirafshari/pythonTutorial/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

### NumPy Array

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
a = [1, 2, 3, 4]

# Dictionary

In [55]:
d = {
    'key': [1,2],
    'a': 12,
    'amir': 'afshari',
    }

In [64]:
l = [('texas', 35000), ('ny', 40000)]

In [65]:
for e in l:
  if e[0] == 'texas':
    print(e[1])

35000


In [56]:
d.keys()

dict_keys(['key', 'a', 'amir'])

In [57]:
d.values()

dict_values([[1, 2], 12, 'afshari'])

In [59]:
d.items()

dict_items([('key', [1, 2]), ('a', 12), ('amir', 'afshari')])

In [60]:
s1 = pd.Series(d)

In [61]:
s1

key      [1, 2]
a            12
amir    afshari
dtype: object

# pd.Series()

In [41]:
obj = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [51]:
l = [1, 2, 3, 4, 5, 6, 5]

In [53]:
for i, e in enumerate(l):
  if e == 5:
    print(i)

4
6


In [52]:
l.index(5)

4

In [46]:
10 in obj

False

In [48]:
2 in [1,2,3]

True

In [42]:
obj['d']

4

In [43]:
obj[[True, True, False, True]]

d    4
b    7
c    3
dtype: int64

In [44]:
obj > 0

d     True
b     True
a    False
c     True
dtype: bool

In [45]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [32]:
a = [2, 3, 4]

In [31]:
a*2

[2, 3, 4, 2, 3, 4]

In [34]:
a.index(3)

1

In [66]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [78]:
s1 = pd.Series([35000, 40000, 12000, 120000], index=['California', 'Texas', 'NY', 'Washington'])

In [79]:
s1.index.name = 'Population'

In [73]:
s1.name = 's1'

In [74]:
s1

City
California     35000
Texas          40000
NY             12000
Washington    120000
Name: s1, dtype: int64

In [98]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [99]:
df = pd.DataFrame(data)

In [100]:
df.index = [10,11,12,13,14,15]

In [101]:
df

state  year  pop
10    Ohio  2000  1.5
11    Ohio  2001  1.7
12    Ohio  2002  3.6
13  Nevada  2001  2.4
14  Nevada  2002  2.9
15  Nevada  2003  3.2

In [102]:
df = df.reset_index(drop=True)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [103]:
df

state  year  pop
10    Ohio  2000  1.5
11    Ohio  2001  1.7
12    Ohio  2002  3.6
13  Nevada  2001  2.4
14  Nevada  2002  2.9
15  Nevada  2003  3.2

### How to multiply every element in a list?

#### Approach 1

In [ ]:
for element in a:
  i = a.index(element)
  a[i] = element*2

#### Approach 2

In [36]:
for i, e in enumerate(a):
  a[i] = e*2

In [37]:
a

[4, 6, 8]

#### Vectorized Way with Numpy

In [38]:
arr = np.array([2,3,4])

In [39]:
arr

array([2, 3, 4])

In [40]:
arr*2

array([4, 6, 8])

In [ ]:
[
    [2,2],
    [2,2],
    [1,1],
]